version: '3.8'

networks:
  default:

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_USER: $MYSQL_USER
      MYSQL_ROOT_HOST: $MYSQL_HOST
      MYSQL_USER: abc
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  nestjs-app:
    container_name: nestjs-app
    build:
      context: ./API
      dockerfile: Dockerfile
      target: install-dependencies
    command: npm run start:dev
    restart: unless-stopped 
    env_file:
      - ./.env
    environment:
      - PORT=$NESTJS_APP_DOCKER_PORT
      - BASE_URL=$BASE_URL
      - DB_TYPE=$DB_TYPE
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_DB=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PORT=$MYSQLDB_DOCKER_PORT
      - MYSQL_SYNC=$MYSQL_SYNC

      - JWT_ACCESS_TOKEN_SECRET=$JWT_ACCESS_TOKEN_SECRET
      - JWT_REFRESH_TOKEN_SECRET=$JWT_REFRESH_TOKEN_SECRET
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=$JWT_ACCESS_TOKEN_EXPIRATION_TIME
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=$JWT_REFRESH_TOKEN_EXPIRATION_TIME
    stdin_open: true
    tty: true
    volumes:
      - ./src:/user/src/app/src
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
      - "9229:9229"
    networks:
      - default
      
  react-app:
    container_name: react-app
    build:
      context: ./FE
      dockerfile: Dockerfile
      target: builder
    command: npm run start
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - $REACT_JS_APP_LOCAL_PORT:$REACT_JS_APP_DOCKER_PORT
    environment:
      - SASS_PATH=$SASS_PATH
      - REACT_APP_PACKAGE_NAME=$REACT_APP_PACKAGE_NAME
      - REACT_APP_BASE_API_URL=$REACT_APP_BASE_API_URL
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/fe
      - /usr/src/fe/node_modules
    networks:
      - default

volumes: 
  mysql-volume: